### ISSUE TITLE
Typos in blog post

### ISSUE THREAD

**Issue by TWiStErRob** [xmlet/HtmlFlow#106]
https://dzone.com/articles/modern-type-safe-template-engines

 * KotlinX Html usage from Java: it's not calling the function, but the ClassName.
 * Similar with HtmlFlow, I think it was meant to be studentView.render, right?

**Comment by fmcarvalho** [comment]
Thanks @TWiStErRob 

I have addressed the typos as per your suggestions. It may take some time for the fixes to be turn visible.

**Comment by fmcarvalho** [comment]
Published
