### ISSUE TITLE
Possible to create component or fragment or partial (customised Element) with any parent?

### ISSUE THREAD

**Issue by kask-service** [xmlet/HtmlFlow#112]
I am trying to create a system of reusable components, example button component:
```
public class ButtonExtended {
  public static Void content(Div<?> view, final ButtonExtendedOptions options) {
    view
      .a()
         .attrClass(CSS.BUTTON + CSS.BUTTON_IMAGE_EXT)
         .attrHref(options.getHref())
         .text(options.getText())
      .__(); // a
      return null;
  }
}
```
One issue is that this component must have a div as a parent.

Example use case (also second question does this approach still take advantage of static HTML blocks? - HtmlView instantiation)
```
public static final ButtonExtendedOptions btnOption = ButtonExtendedOptions.of("text", "/link");
---
.div().of(o -> ButtonExtended.content(o, btnOption)).__()
```

======
Attempted solutions 
I tried Element as it a parent of Div but looks like it's not supposed to be used on own
```
public static Void content(Element<?, ?> view, final ButtonExtendedOptions options) {
```
also tried
```
public static Void content(HtmlView view, final ButtonExtendedOptions options) {
```
but only div and tr and html are allowed as children.
Is there a way to make a component that can have any parent rather than copying the implementation for each parent type?

**Comment by fmcarvalho** [comment]
Yes, you can. 

You just may **instantiate any of the available elements** from the `org.xmlet.htmlapifaster` package and it works with both static (`HtmlDoc`) or dynamic (`HtmlView`) pages.

It is only required a parent `Element` to get its _element visitor_ responsible for emitting the output.

Here is the revised version of your `content` function (I don't know if is that a requirement but I replaced `Void` by `void`. You may exchange it again if you wish):
```java
static void content(Element<?,?> parent, final ButtonExtendedOptions options) {
    new A<>(parent)
            .attrClass(CSS.BUTTON + CSS.BUTTON_IMAGE_EXT)
            .attrHref(options.getHref())
            .text(options.getText())
            .__(); // a
}
```

Now you may use that content in a Dynamic view like the next one. You can replace `section` by any other kind of block Element: 
```java
HtmlView<Object> view = HtmlFlow.view(v -> v
        .html()
          .body()
            .div()
              .section()
                .of(section -> content(section, new ButtonExtendedOptions()))
              .__() // section
            .__() // div
          .__() // body
        .__() // html
    );
view.setOut(System.out).write();
```

Also you may use it in a static page:
```java
HtmlFlow.doc(System.out)
        .html()
          .body()
            .div()
              .section()
                .of(section -> content(section, new ButtonExtendedOptions()))
              .__() // section
            .__() // div
          .__() // body
        .__(); // html
```

**Comment by fmcarvalho** [comment]
@kask-service does it solve this issue?

**Comment by kask-service** [comment]
Yes that solved the issue, thank you for your help!

**Comment by fmcarvalho** [comment]
@kask-service Please, star HtmlFlow repository  for popularity.
