### ISSUE TITLE
Dynamic html to string wrong

### ISSUE THREAD

**Issue by EkkoNunu** [xmlet/HtmlFlow#47]
**Wrong use of DynamicView! You should provide a model parameter or use a static view instead!** method render(T mode), How to define T mode???

**Comment by fmcarvalho** [comment]
It is not more, but model instead. Sometimes called context object in template engines. If you do not have any context object (model) to bind to the view then you should use StaticHtml rather than DynamicHtml.

**Comment by fmcarvalho** [comment]
@EkkoNunu Does this solve your issue?

**Comment by fmcarvalho** [comment]
@EkkoNunu Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
