### ISSUE TITLE
RFP from(html).on(element).do(element -> )

### ISSUE THREAD

**Issue by fmcarvalho** [xmlet/HtmlFlow#49]
Support some how load an existing HTML source and then proceed with HtmlFlow on a given element.

**Comment by pratikpparikh** [comment]
@fmcarvalho has this been added?  Can someone please add this feature.  I would like to make use of HtmlFlow but it requires this feature.

**Comment by fmcarvalho** [comment]
Hi @pratikpparikh. This has not been done yet. While this seems a nice feature I have some doubts about the better way of providing it. 

When I first though on this there was not yet Flowifier. Now, I think Flowifier mitigates this issue.

The way I was thinking this features was something like a layout template (aka master template page). We can build that layout once and then reuse it everywhere. If you already have a static HTML layout page then Flowifier may help you to build that HtmlFlow layout view.

You can check how to use layouts here: https://htmlflow.org/features#layout-and-partial-views-aka-fragments

If you are thinking in a different use case, please describe it to help we understand what would be the better HtmlFlow approach.
