### ISSUE TITLE
How to link css files in Dynamic View

### ISSUE THREAD

**Issue by ZinfinityDarshan** [xmlet/HtmlFlow#58]

**Comment by fmcarvalho** [comment]
You may find different examples in `src/test/java/htmlflow/test/views/` folder. For instance in line 62 of [HtmlDynamicStocks.java](https://github.com/xmlet/HtmlFlow/blob/master/src/test/java/htmlflow/test/views/HtmlDynamicStocks.java) view, you have an example of a `link` to a CSS in a Dynamic view. 

Hope it helps.

**Comment by fmcarvalho** [comment]
@ZinfinityDarshan Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
