### ISSUE TITLE
Story for generating inline css or inline js

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#63]
Does this project plan to produce inline js or inline css.

Using thymleaf it happens from time to time that I need to produce  in my inline js base on some variable extracted from the model.

**Comment by fmcarvalho** [comment]
Can you give an example use case please, for that usage.

**Comment by benzen** [comment]
I'll use the exemple provided in the thymleaf documentation 

```
<script th:inline="javascript">
    ...
    var username = [[${session.user.name}]];
    ...
</script>
```

Here the value from `session.user.name` is used to generate the content of the script.

There is ways to workarround this as a missing feature, like adding data to the dom, that the JS code would pick up on initialisation.

But the way proposed by thymleaf feels quite natural to me. If we decide to not provide support for this feature in htmlflow, I think documentation should guide a developper toward alternatives.

**Comment by fmcarvalho** [comment]
Maybe I am not entirely understanding that use case. But I am not figuring out the need of "_adding data to the dom, that the JS code would pick up on initialisation_".

If I am thinking well when you build a Javascript block in HtmlFlow such as: `....script().text(inlinejs)`, where the `inlinejs` local variable  should be initialized before with the Js code such as `String inlinejs = String.format("... var username = %s", session.user.name)`. Isn't it?

**Comment by benzen** [comment]
This is perfect, especially with brand new textblock feature and the instance method formatted on string.

As I suspected it's just a matter of documentation. Thank you very much.

I propose we keep this issue open, I'll make a PR for enhancing documentation on this point
