### ISSUE TITLE
Add documentation for the api

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#71]
To use this library one have to go check example and extrapolate the possible api.

If this person uses an IDE with autocompletion, no problem, the api can be discovered, but otherwise the path to understanding is pretty rough.

We should add a couple of sections on the api in the documentation.

**Comment by fmcarvalho** [comment]
Yes you are right. 

There a couple of concepts intrinsic to HtmlFlow that should be better explained. Like the difference between using StaticHtml and DynamicHtml. `.dynamic()` or `.of()`. Interface `HtmlTemplate<T>`.  And other things...

**Comment by fmcarvalho** [comment]
I am planning to work on this and make a major refactoring on Documentation and Readme. 

I am also considering anew web theme for Documentation. Maybe this one: https://themes.3rdwavemedia.com/demo/coderdocs/docs-page.html

**Comment by benzen** [comment]
In the proposed them, the single page is very nice.
The way I consume pages is by using cmd+f a lot. So single page is very helpfull to my usage pattern.


In the more visual aspect, I prefer the current color scheme. But what ever, the most important stuff is the content. Color scheme is a lower in the priority of things

**Comment by fmcarvalho** [comment]
To do: evaluate the chance of migrating HtmlFlow site and documentation to https://github.com/pmarsceill/just-the-docs

**Comment by fmcarvalho** [comment]
HtmlFlow site migrated to Jekyll documentation theme.
