### ISSUE TITLE
Documentation enhancement

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#72]
In my opinion, the documentation should be have two (or more) fold.

In one we should find out about how to library works, and how to use it.
In the second part we should find solution for stuff that are not directly related to the library but how we propose to solve common issues.
For exemple how to include translated message. Or  how to deal with conditional part of a template, how to increase usage of cache

In this regard thymleaf team did a great job by explaining how thymleaf can leverage spring

**Comment by fmcarvalho** [comment]
I included the most common use cases for data binding, if/else, and loops usage, in GitHub README.

Also in https://htmlflow.org/features I have included the same examples implemented with both approaches: `HtmlDoc` and `HtmlView`
