### ISSUE TITLE
How to create a custom tag/element?

### ISSUE THREAD

**Issue by iyerha** [xmlet/HtmlFlow#80]
I am evaluating htmlFlow for our project.  We are using web components and don't see how [custom elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) are supported. I see that kotlinx.html has support for the [same](https://github.com/kotlin/kotlinx.html/wiki/Micro-templating-and-DSL-customizing) and I am hoping that htmlFlow has an equivalent feature.

**Comment by fmcarvalho** [comment]
No, we do not have support for custom Elements yet. It is a nice feature and I would like to include it in HtmlFlow DSL. We will have to discuss the best way to do it. But I think that we should place some effort to develop it soon. We will analyze it an then I will give a estimated date here soon.

It would be useful if you could provide your use cases on custom elements use. 

Regarding HTML fragments/partials support and reuse, we can already do it in HtmlFlow in an unopinionated manner. There is some lack of details in documentation but there is a high level idea here about that: https://htmlflow.org/features/#partial-and-layout.

**Comment by fmcarvalho** [comment]
@iyerha we may have 2 options: 

1) Simplest - Similar to existing `.of(elem -> ....)`  that let us chain control flow over the last created element. We may introduce a `custom(<custom tag>, elem ->... )` to let us include a custom element. And, then in the lambda we could add any kind of attributes over that element. In this case, the definition of the custom element itself would be on charge of the programmer that should provide the JavaScript code, e.g. `custom.js`, and link it to the HtmlFlow document through the `script` tag, i.e. `....head().script().attrSrc('custom.js')` 

2) Harder -  Beyond solution 1) we could include an additional DSL to define the custom element itself, where we could take advantage of HtmlFlow to write the HTML of that custom element. But what should be the resulting output? 2 files: html and js? And if we are streaming?

**Comment by iyerha** [comment]
That is the typical usage. Solution 1 looks good enough. On a separate note, we also use custom [data](https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes) attributes in regular html.

**Comment by iyerha** [comment]
All of the above. That is a valid example.

**Comment by fmcarvalho** [comment]
@lcduarte With the new custom element feature we should be able to define HtmlFlow views such as the listing at the end of this comment (this feature applies regardless being a static or a dynamic view). 

I think that invoking `.custom("alert-info")` should return an instance of a new class `CustomElement` that inherits from existing `Div` class. Hence, we will have most HTML features available at the resulting instance.

Moreover, that class `CustomElement` should store the custom tag (e.g. `alert-info`) in some way that will be accessible to the `HtmlVisitor`, which is responsible for printing `<alert-info>`. **NOTICE** that currently the resulting HTML tag is printed through:
```java
@Override
public final void visitElement(Element element) {
    newlineAndIndent();
    if (isWriting()){
        beginTag(element.getName()); // "<elementName"
        isClosed = false;
    }
}
```

So, the `getName()` in the new class `CustomElement` should return the same `String` passed to `.custom(<String>)`, e.g. `alert-info`.

```java
HtmlView viewWithCustomElements() {
    return StaticHtml
        .view()
            .html()
                .head()
                    .script()
                        .attrSrc("alert.js") // Link to alert-info definition
                        .attrDefer(true)
                    .__()
                .__()
                .body()
                    .div()
                        .attrClass("container")
                        .p().text("Testing custom elements!").__()
                        .custom("alert-info") // alert-info should be stored in the new Element and accessible to the Visitor.
                            .addAttr("title", "Information")
                            .addAttr("message", "This is a message for a custom element")
                            .addAttr("kind", "success")
                            .ul()
                                .li().text("For any reason we could even include other elements.").__()
                            .__() // ul
                        .__() // alert-info
                    .__() // div
                .__() // body
            .__(); //html
}
```

**Comment by lcduarte** [comment]
Hello,

This change looks doable, I'll investigate it further on the weekend and I'll prepare the changes needed.

**Comment by lcduarte** [comment]
Hi,

I've made the required changes on our related projects and I've added a new test in the development branch to validate the example provided above.

**Comment by fmcarvalho** [comment]
@iyerha Just released HtmlFlow 3.9 with support for custom elements as announced here: https://htmlflow.org/2022/01/30/Release-3.9/

I will wait a few days and if there is no more updates on this issue I will close it.

**Comment by fmcarvalho** [comment]
@iyerha As you may be aware, I am the author and primary advocate for the HtmlFlow Java library. As part of my continuous endeavors, I am required to provide justification for this project to my university.

HtmlFlow serves as a versatile auxiliary tool utilized across various sectors, facilitating software development by streamlining tasks such as HTML reporting automation, web templating, and more. 

If you have utilized HtmlFlow, I kindly request your testimony regarding my dedication to addressing issues, implementing new features, or otherwise aligning with your requirements and/or your company within the scope of a specific project, task, or work that utilized HtmlFlow during a certain timeframe.

Your testimony will play a crucial role in demonstrating my work to my university.

Please feel free to send your testimonial to my email address at ISEL: [miguel.gamboa@isel.pt](mailto:miguel.gamboa@isel.pt)

Thank you in advance for your attention and assistance.

**Comment by fmcarvalho** [comment]
@iyerha Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
