### ISSUE TITLE
Cannot have full dynamic page

### ISSUE THREAD

**Issue by black-inc-service** [xmlet/HtmlFlow#90]
I am in the progress of moving from 3.9 to 4.0 and needing to do some refactoring as the interface has changed.
I have a setup where a HtmlView only returns a div and not a full page as it is part of an AJAX call.

This only works for div as other tags are not available from HtmlPage, some of my AJAX requests are spans or other elements, although there is the custom function.
```
public class HtmlLists {
	public static HtmlView view = HtmlFlow.view(HtmlLists::taskDetailsTemplate);

	public static class AModel {}

	public static void taskDetailsTemplate(HtmlPage view) {
	    view.<AModel>dynamic((v, mod) -> HtmlLists.taskDetailsTemplateFregment(v.div(), mod) );
	}

	public static void taskDetailsTemplateFregment(Div<?> view, AModel model ) {
	    view.p().text("test").__();
	}

}

	HtmlLists.view.render(new AModel());
```

causes:
```
Exception in thread "main" java.lang.ExceptionInInitializerError
```
It also does not work when no Model is used
```
public static void taskDetailsTemplate(HtmlPage view) {
    view.dynamic((v, mod) -> HtmlLists.taskDetailsTemplateFregment(v.div(), null) ).__();
}
```

The workaround is to use
```
public static void taskDetailsTemplate(HtmlPage view) {
	view.div().<AModel>dynamic((v, mod) -> HtmlLists.taskDetailsTemplateFregment(v, mod) ).__();
}
```
One issue is that the fragments are made to be self closing and set their own id in root element, with the workaround they are double wrapped.
My intention was to make a generic AJAX view which based on the query launch different partial fragments.

**Comment by fmcarvalho** [comment]
Maybe documentation must alert on that part, but fragments should not be used with the root HtmlPage. Let me know, if that is critical for you, but I think the following recommended use may solve your issues. 

In `taskDetailsTemplate ` replace the statement by:
```java
view.div().<AModel>dynamic((div, mod) -> HtmlLists.taskDetailsTemplateFregment(div.div(), mod) ).__();
```

BTW you are not closing the new div passed to the fragment. Thus, the correct view definition should be:

```java
public static void taskDetailsTemplate(HtmlPage view) {
    view
        .div()
        .<AModel>dynamic((div, mod) -> div
            .div()
                .of(innerDivd -> HtmlLists.taskDetailsTemplateFregment(innerDivd, mod) )
            .__()
        )
        .__();
}
```

**Comment by fmcarvalho** [comment]
@black-inc-service Even if you are not currently using HtmlFlow, I kindly request your acknowledgment that I was actively engaged in maintaining, tracking issues, or new features during the time of this issue. It is imperative for me to justify my efforts on HtmlFlow during the period of this issue to my university. 

I would greatly appreciate it if you could once again provide your acknowledgment to my email address at ISEL: miguel.gamboa@isel.pt. 

Thank you in advance for your attention and assistance.
