### ISSUE TITLE
slf4j-simple should not be declared as a dependecy

### ISSUE THREAD

**Issue by kicktipp** [xmlet/HtmlFlow#92]
https://github.com/xmlet/HtmlFlow/blob/c7931c8a4f03c5ad4137e7166f099d5d797faa3e/pom.xml#L50C1-L54C22

slf4j-simple should not be declared as a dependecy, Otheriwse you end up with mulitple bindings and get this error:
https://saturncloud.io/blog/hadoop-slf4j-class-path-contains-multiple-slf4j-bindings/#resolving-the-class-path-contains-multiple-slf4j-bindings-error

workaround:

```
    implementation('com.github.xmlet:htmlflow:4.0') {
        exclude group: 'org.slf4j', module: 'slf4j-simple'
    }
```

**Comment by fmcarvalho** [comment]
That's right. We have already address it in this commit: https://github.com/xmlet/HtmlFlow/commit/e5512a3721c90753ca01c67ad565da51dc921955

Fixed on next release.

**Comment by fmcarvalho** [comment]
Version 4.1 released and solve this issue.
