### ISSUE TITLE
option.attrSelected unexpected behavior

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#94]
when using 
```
option
                               .attrSelected( /*some logic returning true or false*/
````
Ouput might look like this
<img width="550" alt="Capture d’écran, le 2023-10-20 à 00 17 03" src="https://github.com/xmlet/HtmlFlow/assets/139909/9be5d20b-ced6-4880-8c0d-c739c1e2732f">

Which seems fine except, that since selected is a boolean attr, it means that in this exemple every option is selected.
In my opinion it would have been nicer if attrSelected would have not produce anything if the value passed as argument is falsy

**Comment by benzen** [comment]
Here is my way out

```
                            .<ProduitListModel>dynamic((option, model) -> {
                              if(model.form().bois().equals(b)) {
                                 option.attrSelected(true);
                              }
                            }
                            )
```

Uggly but it get's the expected (by me) behavior :)

**Comment by fmcarvalho** [comment]
Your issue is related and with same behaviour  of #89. And the constrain here is the aforementioned:

> HtmlFlow API is automatically generated through an [ASM](https://asm.ow2.io/) pre processor included in our project [XsdAsmFaster](https://github.com/xmlet/XsdAsmFaster) that generates the API from a XSD file with the HTML 5 specification. 

Although I totally agree with you that "_would have been nicer if attrSelected would have not produce anything if the value passed as argument is falsy_". However we cannot easily add new extensions with the desired behaviour that you described.

So your workaround is the right alternative here.

When Java provides extension functions it would be easy to build an auxiliary function wrapping that logic and using it smoothly in an HtmlFlow template.

**Comment by fmcarvalho** [comment]
Maybe, that's a good place.

And, is that the expected behaviour for every HTML boolean attribute set to false?

Can we suppress the emission of any boolean attribute that is false? Would be this safe?
```java
@Override
public final void visitAttribute(String attributeName, String attributeValue) {
    if(!attributeValue.equals(false))
        addAttribute(out, attributeName, attributeValue);
}
```

Or it should be even more like:
```java
@Override
public final void visitAttribute(String attributeName, String attributeValue) {
    if((attributeName.equals("checked") || attributeName.equals("selected")) && !attributeValue.equals(false))
        addAttribute(out, attributeName, attributeValue);
}
```

I don't like the latter.

**Comment by benzen** [comment]
Well, an attriute only need to be present.
But to help out older browser, I think most template engine does is producing a value that match the attribute name.


I think in our case the following should be enough:

```
@Override
public final void visitAttribute(String attributeName, String attributeValue) {
    if(attributeValue.equals("true"))
        addAttribute(out, attributeName, attributeName);
}
```

But the trick is to document how this works
https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#fixed-value-boolean-attributes

REF:
https://developer.mozilla.org/en-US/docs/Glossary/Boolean/HTML

**Comment by fmcarvalho** [comment]
`visitAttribute` is called for all kind of attributes, and not only boolean attributes.

Thus, we can only jump over the call to `addAttribute` for boolean attributes.

**Comment by fmcarvalho** [comment]
Version 4.1 released and solve this issue.
