### ISSUE TITLE
Script tag, attribute type

### ISSUE THREAD

**Issue by benzen** [xmlet/HtmlFlow#97]
According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/script,
script tag can have a type attribute, which could have any of following value

- Absent default dehavior
- import the script pointed by attr src is a importMap
- module the script pointed by src is a js module
- anything else, content won't be processed bu browser and will be assumed to be a data block (unsure what it means).

Anway, the javadoc of html flow doesn't provide an enum for this. Instead [htmlApiFaster-1.0.12-javadoc/org/xmlet/htmlapifaster/EnumTypeScriptType.html#APPLICATION_JAVASCRIPT] provide a list of different version of js. 

It's unclear to me in which case the current behavior of htmlflow is required, but we are missing the module

**Comment by benzen** [comment]
I want to use module to import a js module, 
and also import map in order to change the interprettation of import

**Comment by fmcarvalho** [comment]
OK, I am planning a new release for HtmlApiFaster base on an update to `html_5_2.xsd` that will produce a new with `EnumTypeScriptType`.

```java
public enum EnumTypeScriptType implements EnumInterface<String> {
   IMPORTMAP(String.valueOf("importmap")),
   MODULE(String.valueOf("module")),
   SPECULATIONRULES(String.valueOf("speculationrules")),
```

Then you will able to generate Script tag, with attribute type `module`, such as `.script().attrType(EnumTypeScriptType.MODULE)`.

@benzen  Is that ok to you?

**Comment by benzen** [comment]
Perfect, thanks a lot

**Comment by fmcarvalho** [comment]
Version 4.1 released and solve this issue.
